import Head from "next/head";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";

export default function Home({ newsResults }) {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen  mx-auto ">
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}
        <Feed />
        {/* Widgets */}
        <Widgets newsResults={newsResults.articles} />

        {/* Sidebar */}
      </main>
    </div>
  );
}

// https://saurav.tech/NewsAPI/top-headlines/category/technology/us.json

// fetch api SSR
export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/technology/us.json"
  ).then((res) => res.json());
  return {
    props: {
      newsResults,
    },
  };
}
